"""Add feed.posts_count column

Revision ID: ec9aacfdec27
Revises: c3f4523bf3cd
Create Date: 2020-06-12 14:38:40.490428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9aacfdec27'
down_revision = 'c3f4523bf3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feeds', sa.Column('posts_counts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feeds', 'posts_counts')
    # ### end Alembic commands ###
